### ISSUE TITLE
Аппроксимация геомтерии. Постановка.

### ISSUE THREAD

**Issue by alisovenko** [viktorjaa/geom_june_2022#12]
Основные требования такие:

На вход подается один мультиполигон.
Нужно попытаться уменьшить количество точек и количество отдельных полигонов.
На выходе один мультиполигон.

При этом:
1. оригинальная геометрия должна лежать внутри аппроксимированной
2. у алгоритма должны быть опции:
    1. ограничение максимальное увеличения площади
    2. количество желаемых точек
    3. количество желаемых полигонов

Примерно что мы должны получить:
если нужно сократить до 4 точек (нарисовано от руки для примера, разница между полигонами должна быть меньше):
![image](https://user-images.githubusercontent.com/5332345/175889379-d95578b3-f0fb-4f5e-ae22-0ca1c5d4087c.png)

Группу полигонов нужно объединять, если на выходе нам нужно получить не больше двух полионов:
![image](https://user-images.githubusercontent.com/5332345/175889625-37a7c48f-d146-4e8c-98bd-f4c58aed1f76.png)

---
Тут будем обсуждать этот алгоритм.
На основе этой задачи будем создавать более мелкие задачи.

**Comment by viktorjaa** [comment]
Возможен такой вариант решения.

Сначала уменьшается число полигонов до заданного значения.
При таком действии увеличивается площадь, уменьшается число полигонов, количество вершин должно оставаться неизменным.
В простом случае может быть так.
1. Исходная картина
![2022-06-28_10-07-06 1 два треугольника](https://user-images.githubusercontent.com/106670245/176119291-ca73e0cd-2a5a-4559-a052-7f3968a1eb7a.png)
2. Построили "перетяжку" с наименьшей возможной площадью.
![2022-06-28_10-08-32 2 склеили в один](https://user-images.githubusercontent.com/106670245/176119293-168d5b3c-bab8-4406-a543-91e40f2077d3.png)
3. Полученная картина после объединения.
![2022-06-28_10-09-00 склеили в один](https://user-images.githubusercontent.com/106670245/176119295-29fdf623-2ed5-44aa-aabe-66f4b6e76e1f.png)

После получения нужного количества полигонов уменьшается количество вершин до желаемого за счет увеличения площади. К полигону присоединяются треугольники, на каждом шаге - с самой маленькой площадью. За счет присоединения треугольника можно либо убрать одну невыпуклую вершину, либо заменить две выпуклых на одну.
Пример может выглядеть так:

1.
![2022-06-28_10-15-17 упрощение 0](https://user-images.githubusercontent.com/106670245/176120900-03f33ced-f128-4dcc-a123-003d32fb5a12.png)
2. Здесь убрана невыпуклая вершина
![2022-06-28_10-15-32 упрощение 1](https://user-images.githubusercontent.com/106670245/176120904-43cb4ea7-12a6-4e46-a7ed-34ec0fdb8cf6.png)
3. Здесь вместо двух выпуклых вершин получена одна. Две исходные вершины лежат на сторонах, которые подходят к новой вершине.
![2022-06-28_10-16-27 упрощение 2](https://user-images.githubusercontent.com/106670245/176120905-d08cefa6-5726-445b-a99e-bd5f08b3ec5f.png)
4.
![2022-06-28_10-17-19 упрощение 3](https://user-images.githubusercontent.com/106670245/176120908-f508bc88-00b4-4cd2-8858-26a67fb5beb7.png)
5.
![2022-06-28_10-17-48 упрощение 4](https://user-images.githubusercontent.com/106670245/176120910-30b445b0-4471-481b-823f-093094112d0c.png)
6.
![2022-06-28_10-18-09 упрощение 6](https://user-images.githubusercontent.com/106670245/176120912-3ff510d0-6675-4d7f-b99a-0378d69ea222.png)
7.
![2022-06-28_10-18-43 упрощение 8](https://user-images.githubusercontent.com/106670245/176120914-b4855892-3be4-4c54-bca2-e73ba849986a.png)
8.
![2022-06-28_10-19-36 упрощение 9](https://user-images.githubusercontent.com/106670245/176120917-00b093e7-5bc6-48fd-b4db-9b8d6cb9a378.png)
9.
![2022-06-28_10-20-06 упрощение 10](https://user-images.githubusercontent.com/106670245/176120920-0a1ac4bb-f32b-4e8b-9ca4-7a8700f9c6f8.png)

Как определяется выпуклость вершины - через две соседние проводится линия, и проверяется, попадает ли она внутрь полигона.

Когда останавливается алгоритм - превышено ограничение добавляемой площади либо достигнуто желаемое количество полигонов и вершин.

**Comment by viktorjaa** [comment]
Вариант для уменьшения количества полигонов.

1. get_lines - собирает только отрезки с границ полигонов, без всей паутины между ними.
2. get_quads - стоит четырехугольники с двумя сторонами из отрезков с границ. Если для каждой пары полигонов перебирать каждую пару ребер - перебор будет работать примерно как сейчас(со всеми доступными отрезками между полигонами). Можно для каждой пары полигонов искать единственный вариант "моста" без перебора всех пар ребер: на двух самых коротких отрезках, или менее удаленных друг от друга. Принцип отбора пока не совсем понятен.
3. get_bridges -  самый приоритетный "мост" добавляется, "пересекающие" его мосты исключаются, в рассмотрение попадают новые "мосты", которые можно построить к добавленному из несоединенных к нему полигонов.

**Comment by viktorjaa** [comment]
При уменьшении количества точек может возникнуть наложение разных полигонов
![image](https://user-images.githubusercontent.com/106670245/178673785-594aaba1-aa69-4c58-a204-9de113117eda.png).

Возможное решение: во время упрощения объединить наложенные полигоны, затем упростить снова.

**Comment by viktorjaa** [comment]
Уменьшение количества точек.
Для каждого полигона
1. Построить буффер (https://shapely.readthedocs.io/en/stable/manual.html#object.buffer), радиус - buffer_rad.
Возможный вариант buffer_rad = perimeter / amount_of_points
2. Упростить полученный результат (https://shapely.readthedocs.io/en/stable/manual.html#object.simplify). 
tolerance = buffer_rad * k. Скорее всего k = 1, но могут возникать исключительные случаи, где 1 не подойдет.
3.  Корректно собрать их в мультиполигон.

Разобраться tolerance и buffer_rad могут влиять на количество вершин, (добавленную площадь к полигону) и покрытие полученного исходным(пока что не всегда срабатывает, площадь "вылезших кусков" меньше 1e-16).

**Comment by viktorjaa** [comment]
Поиск способа задать значение буффера от заданного количества вершин (m) и параметров полигонов.

1.) Количество вершин при построении буффера и его упрощении не учитывается, непредсказуемое и, видимо, зависит от характера входных данных.
2.) При этом чем меньше нужно вершин, тем больший буффер нужно строить. Зависимость для входных данных из примера следующая: 
![image](https://user-images.githubusercontent.com/106670245/179253563-41b10e70-5d06-4faf-be2e-4183198fa827.png)
3.)Можно попробовать вывести зависимость для упрощения на примере правильного многоугольника с большим числом вершин.
