### ISSUE TITLE
Flask app

### ISSUE THREAD

**Issue by alisovenko** [viktorjaa/geom_june_2022#2]
Нам нужно разработать веб-приложение.
Приложение, которое будет принимать запросы по сети и возвращать ответы.

В этом нам поможет Flask.
Устанавливается просто: 
`pip install Flask`

Простое приложение на Flask можно найти тут 
https://flask.palletsprojects.com/en/2.1.x/quickstart/#a-minimal-application

Сейчас задача:
1. немного поменять структуру репозитория:
1.1 исходный код поместить папку src
1.2 тесты поместить в папку tests
1.3 в корень проекта добавить файл requirements.txt - в этом файле должны быть перечислены пакеты, которые нужны для работы нашего приложения: shapely и Flask.
пример: (https://github.com/binder-examples/requirements/blob/master/requirements.txt)

2. создать Flask приложение, как в примере.
2.1 при запуске приложения в браузере по url http://127.0.0.1:5000/ мы должны увидеть Hello, World!

Следующим шагом мы подключим уже готовую функцию расчета параметров полигона к веб приложению.

**Comment by viktorjaa** [comment]
Flask приложение как в примере - https://github.com/viktorjaa/geom_june_2022/commit/3c2c8e756206b9c7b4fd02772fb19200eea3bd10
